# s3 슬꺼로 바꿈
server:
  port: 0
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: todak
            client-secret: todak
            scope: account_email, profile_nickname
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: todak
    username: todak
    password: todak
    tomcat:
      max-active: 5
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      maxFileSize: 5120MB # 최대 5GB
      maxRequestSize: 5120MB # 최대 5GB

  # Email settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: todak
    password: todak
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  redis:
    host: todak
    port: todak
    #password: 1234
  application:
    name: member-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      #      groupid는 consumer 그룹을 식별하는 id 이다. 동일한 그룹ID를 가진 컨슈머들은 메시지를 분담해서 consume.
      group-id: payment-group
      #      가장 처음으로 사용가능한 메시지부터 읽기 시작.
      auto-offset-reset: earliest
      enable-auto-commit: false
    chat:
      consumer:
        group-id: chat-group
        auto-offset-reset: earliest
        enable-auto-commit: false

jwt:
  secret: secret_key
  secretKeyRT: secret_key_RT
  expirationRT: 86400000
  expiration: 86400000  # 1 day in milliseconds

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key : todak
      secret-key : todak
    region:
      static: ap-northeast-2
    s3:
      bucket: todak-file
eureka:
  client:
    serviceUrl:
      #      eureka의 member-service(서비스)로서 등록됨을 지정하겠다.
      defaultZone: http://eureka:8761/eureka/

aws:
  ses:
    access-key: todak # 액세스 키 ID
    secret-key: todak # 보안 액세스 키
    region: ap-northeast-2
encryption:
  secret-key: todak